=== Ramilcheq/Facts/src/test/java/Files/xml_files/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- definition of simple types -->
    <xs:simpleType name="Fact">
        <xs:restriction base="xs:string">
            <xs:pattern value="\_*[A-Za-z]+[A-Za-z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- definition of complex types -->
    <xs:complexType name="FactExpression">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="fact" use="required" type="Fact"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="AndExpression">
        <xs:sequence>
            <xs:element name="Fact" type="FactExpression" maxOccurs="unbounded" minOccurs="2"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OrExpression">
        <xs:choice maxOccurs="unbounded" minOccurs="2">
            <xs:element name="And" type="AndExpression"/>
            <xs:element name="Fact" type="FactExpression"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Rule">
        <xs:sequence>
            <xs:choice>
                <xs:element name="Or" type="OrExpression"/>
                <xs:element name="And" type="AndExpression"/>
                <xs:element name="Fact" type="FactExpression"/>
            </xs:choice>
            <xs:element name="Result" type="Fact"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Rules">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:element name="Rule" type="Rule"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FactsType">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:element name="Fact" type="Fact"/>
        </xs:sequence>
    </xs:complexType>

    <!-- definition of elements -->
    <xs:element name="Rules_Facts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rules" type="Rules"/>
                <xs:element name="Facts" type="FactsType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Ramilcheq/Facts/src/test/java/Files/xml_files/Exception9.xml
<Rules_Facts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="schema.xsd">
    <Rules>
        <Rule>
            <Fact fact="aa"/>
        </Rule>
    </Rules>
    <Facts>
        <Fact>_a3</Fact>
        <Fact>A</Fact>
        <Fact>a3</Fact>
        <Fact>A3</Fact>
        <Fact>Aa3</Fact>
        <Fact>a_3</Fact>
        <Fact>____________________a</Fact>
        <Fact>_________a3</Fact>
        <Fact>Aaaaa3</Fact>
    </Facts>
</Rules_Facts>

=== Ramilcheq/Facts/src/test/java/Files/xml_files/1.xml
<Rules_Facts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:noNamespaceSchemaLocation="schema.xsd">
    <Rules>
        <Rule>
            <Or>
                <And>
                    <Fact fact="b"/>
                    <Fact fact="b"/>
                </And>
                <And>
                    <Fact fact="b"/>
                    <Fact fact="b"/>
                </And>
            </Or>
            <Result>d</Result>
        </Rule>
        <Rule>
            <And>
                <Fact fact="b"/>
                <Fact fact="b"/>
            </And>
            <Result>d</Result>
        </Rule>
        <Rule>
            <And>
                <Fact fact="b"/>
                <Fact fact="b"/>
            </And>
            <Result>d</Result>
        </Rule>
        <Rule>
            <Fact fact="b"/>
            <Result>d</Result>
        </Rule>
        <Rule>
            <And>
                <Fact fact="b"/>
                <Fact fact="b"/>
            </And>
            <Result>d</Result>
        </Rule>
        <Rule>
            <Or>
                <And>
                    <Fact fact="b"/>
                    <Fact fact="b"/>
                </And>
                <Fact fact="b"/>
            </Or>
            <Result>d</Result>
        </Rule>
        <Rule>
            <Or>
                <Fact fact="a"/>
                <Fact fact="b"/>
                <Fact fact="c"/>
                <Fact fact="sa"/>
            </Or>
            <Result>d</Result>
        </Rule>
        <Rule>
            <Or>
                <Fact fact="a"/>
                <And>
                    <Fact fact="b"/>
                    <Fact fact="c"/>
                </And>
                <Fact fact="sa"/>
            </Or>
            <Result>d</Result>
        </Rule>
        <Rule>
            <Or>
                <Fact fact="E"/>
                <And>
                    <Fact fact="AD"/>
                    <Fact fact="F"/>
                    <Fact fact="K"/>
                </And>
                <Fact fact="aa"/>
                <And>
                    <Fact fact="Q"/>
                    <Fact fact="W"/>
                </And>
                <Fact fact="aq"/>
            </Or>
            <Result>I</Result>
        </Rule>
        <Rule>
            <Fact fact="C"/>
            <Result>D</Result>
        </Rule>
    </Rules>
    <Facts>
        <Fact>_a3</Fact>
        <Fact>A</Fact>
        <Fact>a3</Fact>
        <Fact>A3</Fact>
        <Fact>Aa3</Fact>
        <Fact>a_3</Fact>
        <Fact>____________________a</Fact>
        <Fact>_________a3</Fact>
        <Fact>Aaaaa3</Fact>
    </Facts>
</Rules_Facts>

=== Ramilcheq/Facts/src/test/java/Files/xml_files/4.xml
<Rules_Facts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="schema.xsd">
    <Rules>
        <Rule>
            <And>
                <Fact fact="_ds234_"/>
                <Fact fact="b"/>
            </And>
            <Result>d</Result>
        </Rule>
    </Rules>
    <Facts>
        <Fact>Aa______32aaa3</Fact>
    </Facts>
</Rules_Facts>
